baseURL = "https://urugan.bangunan.co/"
languageCode = "id"
title = "Urugan Bangunan | Jual Material Urugan Sirtu Tanah Berangkal Sirdam Makadam Puing"
theme = "saeseen-hugo"
summaryLength = 25
paginate = 6

[permalinks]
  post = "/:slug/"
  page = "/:slug/"
  category = "/:slug/"

[params]
  meta_description = "Supplier Material Urugan - Jual Sirtu, Tanah Berangkal, Sirdam, Makadam, dan Puing dengan harga bersaing serta gratis biaya pengiriman dan bongkar."
  # Site-wide settings
  viewport = "width=device-width, initial-scale=1.0"
  fontawesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
  logo = "/images/logo/bangunanco-logo-web.png"
  logo_amp = "/images/logo/bangunanco-512x512.png"
  footer_logo = "/images/logo/bangunanco-logo-putih.png"
  favicon = "/images/logo/bangunanco-512x512.png"
  featured_image = "/images/admin/featured-image.png"
  author = "K. Yaman"
  telepon = "//+6285776786091"
  whatsapp = "//api.whatsapp.com/send?phone=6285776786091&text=*Halo bangunan.co*%20%3A"
  enableWhatApps = true
  enableTelepon = true
  tocMinWordCount = 300
  tableOfContent = "Daftar Isi:"
  geo_latitude = -6.595038
  geo_longitude = 106.817787
  opening_hours = "Mo-Sa 08:00-17:00"

  # Schema settings
  keywords = ["jual material", "sirtu", "berangkal", "sirdam", "makadam", "batu kapur", "basecose", "tanah", "material urugan"]
  base_price = 1900000
  price_range = 200000
  free_shipping = true
  materials = [
    "Pasir urug sirtu berangkal makadam tanah",
    "Pasir urug sirtu berangkal sirdam tanah",
    "Pasir urug sirtu berangkal limestone tanah",
    "Pasir urug sirtu berangkal basecose tanah",
    "Pasir urug sirtu brangkal batu kapur tanah"
  ]
  categories = ["Material Bangunan", "Bahan Urugan", "Urugan"]
  payment_methods = ["COD (Cash On Delivery)", "Transfer Bank", "Bayar Ditempat", "Transfer Setelah Terkirim"]
  area_served = ["Jakarta", "Bogor", "Depok", "Tangerang", "Bekasi", "Cikarang", "Karawang", "Subang", "Cikampek", "Purwakarta", "Rangkas Bitung", "Serang"]
  return_policies = [
    "Barang bisa ditukar dalam 1 hari jika tidak sesuai.",
    "Barang dapat ditolak jika material tidak sesuai.",
    "Pengembalian gratis untuk barang yang tidak sesuai."
  ]

 # Hero Section
  hero_image = "/images/admin/bg_bangunanco.png"
  hero_title = "Supplier Material Urugan Terpercaya"
  hero_description = "Kami menyediakan berbagai jenis material urugan seperti Sirtu, Tanah Berangkal, Sirdam, Makadam, Limestone dan Puing untuk kebutuhan pemdatan lahan dan penimbunan. Layanan pengiriman cepat dan gratis ongkir serta bongkar."
  hero_cta_text = "Pelajari Lebih Lanjut"
  services_cta_text = "Cek Katalog Material Urugan"

  # Footer Section
  footer_about_title = "Mengapa Memilih Kami"
  footer_about_description = "Kami menawarkan material urugan dengan jenis yang lengkap dengan harga murah serta free biaya pengiriman dan bongkar. Gratis konsultasi untuk membantu Anda memilih material yang tepat untuk proyek pengurugan Anda."
  footer_services_title = "Kenapa Pilih Kami"
  footer_contact_title = "Kontak Kami"
  footer_bottom_text = "@2024 Bangunan.co. Semua Hak Dilindungi."

  # Testimonials Section
  testimonials_title = "Apa Kata Klien Kami"

  [[params.footer_services]]
  text = "urugan.bangunan.co menawarkan berbagai jenis material urugan seperti Sirtu, Tanah Berangkal, Sirdam, Makadam, Limestone dan Puing. Kami berkomitmen untuk menyediakan material berkualitas tinggi dengan harga bersaing. Pilih kami untuk kebutuhan material proyek pengurugan Anda."

  [[params.footer_contact]]
    icon = "fas fa-map-marker-alt"
    text = "Jalan Lkr. Dramaga No. 09, Bogor - JaBar"
  [[params.footer_contact]]
    icon = "fas fa-phone-alt"
    text = "+62 857-7678-6091"
  [[params.footer_contact]]
    icon = "fas fa-envelope"
    text = "bangunanco@gmail.com"

[[params.testimonials]]
  avatar = "/images/admin/avatar1.png"
  name = "{Budi|Joko|Andi|Eko|Rudi|Fajar|Hendra|Samsul|Agus|Dedi}"
  message = "{Saya membeli {makadam|tanah urug|material bangunan} dari urugan.bangunan.co untuk proyek {jalan|pemadatan tanah|pengurugan tanah}. Kualitas material {sangat baik|memuaskan|terbaik}, dan pengirimannya {tepat waktu|cepat dan aman|sesuai jadwal}.|Material dari urugan.bangunan.co {sangat cocok|sesuai|luar biasa} untuk proyek {urugan tanah|pemadatan jalan|pembangunan jalan} saya. Proses pembelian dan pengirimannya {cepat|lancar|tepat waktu} serta {tanpa hambatan|aman}.}"
  response = "{Terima kasih atas {kepercayaan|ulasan|testimoni} Anda! Kami senang dapat menyediakan material {berkualitas|terbaik|yang Anda butuhkan} untuk proyek Anda.|Kami sangat menghargai ulasan Anda. Senang mendengar bahwa Anda puas dengan layanan kami.|Kami berkomitmen untuk {menyediakan|memberikan} material {terbaik|berkualitas tinggi} dengan layanan {optimal|maksimal}. Terima kasih atas {kepercayaannya|penghargaannya}}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar2.png"
  name = "{Siti|Rina|Dewi|Ayu|Lina|Maya|Nina|Putri|Ratna|Ika}"
  message = "{urugan.bangunan.co sangat {membantu|berperan penting} dalam memilih material {urugan|tanah urug|pengurugan} yang {tepat|sesuai} untuk {proyek|pembangunan} saya. Material yang saya beli {terbaik|sangat cocok|memuaskan} dan sesuai dengan {ekspektasi|kebutuhan|harapan} saya.|Pelayanan dari urugan.bangunan.co {sangat baik|memuaskan|ramah}, dan material yang saya pesan {berkualitas|luar biasa|sesuai} untuk proyek {rumah|pemadatan tanah|pengurugan} saya.}"
  response = "{Kami sangat menghargai ulasan Anda. Senang mendengar bahwa Anda puas dengan material kami.|Terima kasih atas {kepercayaannya|testimoni positifnya}! Kami senang dapat membantu mewujudkan proyek Anda dengan material {terbaik|berkualitas tinggi}.|Kami selalu berusaha {memberikan|menyediakan} pelayanan dan material {terbaik|berkualitas tinggi}. Terima kasih, atas ulasannya!}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar3.png"
  name = "{Joko|Andi|Eko|Rudi|Hendra|Fajar|Agus|Dedi|Budi|Samsul}"
  message = "{Material urugan tanah dari urugan.bangunan.co {sangat sesuai|cocok|tepat} untuk proyek {urugan perumahan|pemadatan tanah|pengurugan} saya. Proses pembelian dan pengirimannya {cepat|tepat waktu|lancar} serta {aman|tanpa hambatan|sesuai harapan}.|Saya sangat puas dengan kualitas material {berangkal|urugan|makadam} dari urugan.bangunan.co. Materialnya {berkualitas|sangat baik|luar biasa} dan cocok untuk proyek {pemadatan tanah|urugan|pembangunan} saya.}"
  response = "{Terima kasih, atas kepercayaannya! Kami senang dapat menyediakan material berkualitas tinggi untuk proyek Anda.|Kami sangat senang mendengar bahwa Anda puas dengan layanan kami. Terima kasih atas ulasannya!|Senang mendengar Anda puas dengan produk kami. Terima kasih atas kepercayaannya!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar4.png"
  name = "{Anto|Rizki|Hadi|Deni|Wawan|Bayu|Iwan|Irwan|Bambang|Yusuf}"
  message = "{Pelayanan urugan.bangunan.co {sangat memuaskan|terbaik|luar biasa}. Material {sirtu|urugan|tanah urug} yang saya beli sangat {berkualitas|baik|memuaskan} dan sesuai dengan {kebutuhan|harapan|rencana} proyek saya.|Material yang saya beli dari urugan.bangunan.co sangat {cocok|sesuai|tepat} untuk proyek {rumah|pemadatan tanah|pembangunan} saya. Proses pengirimannya {tepat waktu|cepat|lancar} dan {aman|tanpa masalah|sesuai harapan}.}"
  response = "{Terima kasih! Kami senang dapat membantu mewujudkan proyek Anda dengan material {terbaik|berkualitas}.|Kami sangat menghargai ulasan positif Anda. Terima kasih atas kepercayaannya!|Kami berkomitmen untuk menyediakan material {terbaik|berkualitas tinggi} dengan layanan {terbaik|memuaskan}. Terima kasih atas ulasannya!}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar5.png"
  name = "{Siti|Rina|Dewi|Ayu|Lina|Maya|Nina|Putri|Ratna|Ika}"
  message = "{Material dari urugan.bangunan.co {sangat sesuai|tepat|cocok} dengan kebutuhan proyek {pengurugan rumah|jalan|pembangunan} saya. Proses pengirimannya {cepat|tepat waktu|lancar} dan {aman|sesuai harapan}.|Saya membeli material urugan dari urugan.bangunan.co untuk proyek {rumah|jalan|pembangunan}. Kualitas material {sangat baik|terbaik|memuaskan}, dan pengirimannya tepat waktu.}"
  response = "{Kami senang mendengar bahwa Anda puas dengan produk kami. Terima kasih atas ulasannya!|Terima kasih atas kepercayaannya! Kami senang dapat menyediakan material berkualitas untuk proyek Anda.|Kami sangat menghargai ulasan positif dari Anda. Senang bekerja sama dengan Anda!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar6.png"
  name = "{Budi|Eko|Rudi|Fajar|Hendra|Samsul|Agus|Dedi|Andi|Joko}"
  message = "{urugan.bangunan.co sangat membantu saya dalam memilih material {sirtu|berangkal|urugan}. Material yang saya beli {sangat cocok|tepat|sesuai} untuk proyek {rumah|perumahan|pembangunan} saya.|Saya sangat puas dengan pelayanan urugan.bangunan.co. Material {sirtu|urugan|tanah urug} yang saya beli {sesuai dengan|memenuhi} kebutuhan proyek saya.}"
  response = "{Terima kasih, atas ulasannya! Kami senang mendengar Anda puas dengan layanan kami.|Kami sangat menghargai ulasan positif Anda. Terima kasih atas kepercayaannya!|Terima kasih, kami senang dapat menyediakan material terbaik untuk proyek Anda.}"
  rating = 5

[[params.tabelItems]]
  name = "Sirtu"
  price = "1.700.000 /truk"
[[params.tabelItems]]
  name = "Brangkal"
  price = "1.700.000 /truk"
[[params.tabelItems]]
  name = "Basecose"
  price = "2.100.000 /truk"
[[params.tabelItems]]
  name = "Makadam"
  price = "2.000.000 /truk"
[[params.tabelItems]]
  name = "Tanah-Merah"
  price = "1.250.000 /truk"
[[params.tabelItems]]
  name = "Limestone"
  price = "1.700.000 /truk"

[params.appliList]
  Sirtu = "lantai, Jalan"
  Brangkal = "lantai, Jalan, Lapangan"
  Basecose = "lantai, Jalan raya"
  Makadam = "lantai, Jalan"
  Tanah-Merah = "lantai, Jalan, Kebun, Taman"
  Limestone = "lantai, Jalan, Sawah"

[params.kegunaanList]
  Sirtu = "Pemadatan dan urug lantai, Jalan"
  Brangkal = "Pemadatan dasar lantai, Jalan, Lapangan"
  Basecose = "Pemadatan lantai, Jalan raya"
  Makadam = "Pengurugan dasar lantai, Jalan"
  Tanah-Merah = "Pengurugan lantai, Jalan, Kebun, Taman"
  Limestone = "Pemadatan dasar tanah, Jalan, Sawah"

  # Menu Section
  [[params.menu_items]]
    title = "Beranda"
    url = "/"
  [[params.menu_items]]
    title = "Profile"
    url = "https://bangunan.co/profile/"
  [[params.menu_items]]
    title = "Daftar Harga"
    url = "https://bangunan.co/daftar-harga/"

[params.header]
  title = "Supplier Material Urugan Terlengkap | "
  highlight = "Bangunan.co"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "AMP"]

[outputFormats]
  [outputFormats.AMP]
    mediaType = "text/html"
    baseName = "amp/index"
    path = ""
    isPlainText = false
    permalinkable = true
    rel = "amphtml"